
==================
Description
==================

This is a C# library allowing you to output morse code to a console (printing and the beep character).


=====
Usage
=====

Import by adding the DLL file (Dynamic Link Library) to your references (Visual Studio), then simply add ``using MorseCode;`` to the beginning of your file.

To play a string, use ``Morse.Play(string);``.
This function writes to the console when called. It does not return anything.

To convert english to morse code, use ``Morse.ToMorse(string);``
To convert morse code to english, use ``Morse.ToEng(string);``
These 2 functions return values that are the converted versions. If you encounter an error, it will return the error message.
For these 2 functions, for the parameter string, you have to type in 1 character from english or morse code, depending on which function you choose.

There is also 2 dictionaries that you can use!
``Morse.CharsToMorse`` & ``Morse.CharsToEng``.
I hope you enjoy this library!

IMPORTANT NOTES:
When translating to english from morse code, a space is defined with a forward slash, like this ``/``.
Also separate different morse code characters with a space.

==================
THANK YOU FOR USING OUR LIBRARY!
==================
